### ISSUE TITLE
[E]  NoSuchMethodError: The method 'split' was called on null

### ISSUE THREAD

**Issue by easazade** [westracer/fontify#15]
I get the following error when i run `fontify` 
```shell
[I]  Using config fontify.yaml
[E]  NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(RegExp: pattern=[\s|,] flags=)
```

This is my config file

```yaml
fontify:
  input_svg_dir: "cityapp/"
  output_font_file: "cityapp/fonts/my_icons_font.otf"
  
  output_class_file: "cityapp/my_icons.dart"
  class_name: "MyIcons"
  indent: 4
  package: my_font_package

  font_name: "My Icons"
  normalize: true
  ignore_shapes: true

  recursive: true
  verbose: false
```
